### PR TITLE
goToTop issues

### PR DESCRIPTION
**Pull request by acatalina**
Modify goToTop as I was having issues while combining it with ScrollableAnchors not been able to go to anchors after going to top.

### CODE REVIEW

**Comment by acatalina** [comment]
you could have a look an example on the website a built using the library, [speedy movers](www.speedy-movers.co.uk).
On the mobile version, there is a menu under the logo. Try to click on Movers that uses goToTop and then click any of the others :)

**Comment by acatalina** [comment]
I have noticed as well you have the same issue in your example page if you click twice on Example and then click on a Section

**Comment by gabergg** [comment]
Thanks for the catch on the issue. This fixes that particular case, but it breaks some other goToTop cases. I just opened a PR which I think will fix it. Hopefully you can pull the new version and let me know if it works for you? Plan to merge shortly: https://github.com/gabergg/react-scrollable-anchor/pull/6

**Comment by gabergg** [comment]
Closing, as this bug should be fixed by https://github.com/gabergg/react-scrollable-anchor/pull/6

**Pull request closed without merging**
