### PR TITLE
#32 - Option to disable automatic URL hash updates

### PR DESCRIPTION
**Pull request by spik3s**
Added a `scrollUrlHashUpdate` config option ( `true` by default ) and wrapped `handleScroll()` inner code in a conditional statement.

Also, according to webpack, Examples needed `react-dom` dependency to run, updated the `package.json`

### CODE REVIEW

**Comment by tlvenn** [comment]
Hi @gabergg, any chance to review this PR and merge it please ? I have the exact same need. This automatic has update on scroll is causing a lot of jitter on mobiles...

Thanks in advance.

**Comment by wallawe** [comment]
@gabergg is this project still being maintained? Please consider adding someone else as a maintainer if you don't have the time.

**Comment by Smmaca** [comment]
I also need this. Has anyone managed to get in contact with the maintainer?

**Comment by Amantel** [comment]
Hmm... what are pro-tips about this situation? 
While we are waiting for @gabergg  this may help: https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a

**Pull request closed without merging**
